const KEYS={products:'noki_products_v1',cart:'noki_cart_v1',wish:'noki_wishlist_v1',theme:'noki_theme_v1',order:'noki_last_order'};
const seed=[
['Wireless Headphone','Electronics',1499,2000,25,'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80','Noki Audio','Comfortable wireless headphones with clear sound and long battery life.','Battery: 30 hours\nConnectivity: Bluetooth\nColor: Black'],
['Smart Watch','Watches',1999,2800,29,'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80','Noki Wear','Smart watch for daily activity, notifications and fitness tracking.','Display: 1.7 inch\nBattery: Up to 7 days\nWater resistance: Yes'],
['Gaming Controller','Gaming',1299,1800,28,'https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=900&q=80','Noki Gaming','Responsive controller for compatible gaming devices.','Connection: Wireless\nLayout: Dual analog\nColor: Black'],
['Mobile Phone','Mobiles & Tablets',18999,22000,14,'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80','Noki Mobile','Modern smartphone with a bright display and capable camera system.','Display: 6.5 inch\nStorage: 128 GB\nRAM: 8 GB'],
['Premium Sneakers','Shoes',2499,3200,22,'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80','Noki Fashion','Everyday sneakers designed for comfortable casual use.','Material: Synthetic\nSole: Rubber\nSizes: 39-44'],
['Travel Backpack','Bags',1299,1700,24,'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80','Noki Bags','Lightweight backpack for school, travel and everyday carrying.','Capacity: 25 L\nMaterial: Polyester\nCompartments: 4'],
['Gaming Mouse','Gaming',899,1200,25,'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80','Noki Gaming','Accurate mouse with ergonomic shape for gaming and work.','DPI: Up to 6400\nConnection: USB\nButtons: 6'],
['Mechanical Keyboard','Computers & Laptops',2199,2800,21,'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80','Noki Tech','Mechanical-style keyboard with comfortable key response.','Layout: Full size\nConnection: USB\nBacklight: Yes'],
['Laptop Pro 14','Computers & Laptops',69999,78000,10,'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80','Noki Tech','Slim laptop for study, office work and creative tasks.','Display: 14 inch\nRAM: 16 GB\nStorage: 512 GB SSD'],
['Bluetooth Speaker','Electronics',1799,2300,22,'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80','Noki Audio','Portable speaker with balanced sound for indoor and outdoor use.','Battery: 12 hours\nBluetooth: 5.3\nCharging: USB-C'],
['Classic T-Shirt','Fashion',699,900,22,'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80','Noki Fashion','Soft everyday T-shirt with a simple classic fit.','Material: Cotton\nFit: Regular\nSizes: S-XXL'],
['Casual Hoodie','Fashion',1499,1900,21,'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80','Noki Fashion','Comfortable hoodie for casual daily wear.','Material: Cotton blend\nFit: Regular\nSizes: M-XXL'],
['Leather Wallet','Accessories',799,1100,27,'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80','Noki Accessories','Compact wallet with multiple card and cash sections.','Material: Leather-look\nSlots: 8\nColor: Brown'],
['Desk Lamp','Home & Living',999,1400,29,'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80','Noki Home','Simple desk lamp for study and work spaces.','Power: LED\nModes: 3\nInput: USB'],
['Coffee Maker','Home & Living',3499,4200,17,'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=80','Noki Home','Compact coffee maker for easy home brewing.','Capacity: 1.2 L\nPower: 900 W\nFilter: Reusable'],
['Study Backpack','Bags',1099,1500,27,'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&w=900&q=80','Noki Bags','Practical backpack with space for books and accessories.','Capacity: 20 L\nMaterial: Nylon\nLaptop sleeve: Yes'],
['Notebook Set','Books',399,550,27,'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=900&q=80','Noki Books','Set of notebooks for school, notes and creative work.','Pages: 160 each\nPaper: Ruled\nPack: 3'],
['Beauty Mirror','Beauty',899,1200,25,'https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=900&q=80','Noki Beauty','Compact mirror with bright adjustable lighting.','Light: LED\nPower: USB\nMagnification: 2x'],
['Tablet 10','Mobiles & Tablets',15999,18500,14,'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80','Noki Mobile','Portable tablet for study, entertainment and browsing.','Display: 10.1 inch\nStorage: 128 GB\nWi-Fi: Yes'],
['Smart Camera','Electronics',5499,6500,15,'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80','Noki Vision','Compact digital camera for everyday photography.','Resolution: 24 MP\nVideo: Full HD\nStorage: microSD']
];
function getProducts(){let p=JSON.parse(localStorage.getItem(KEYS.products)||'null');if(!Array.isArray(p)||!p.length){p=seed.map((x,i)=>({id:'p'+(i+1),name:x[0],category:x[1],price:x[2],oldPrice:x[3],discount:x[4],image:x[5],seller:x[6],description:x[7],specs:x[8],rating:4+(i%2),stock:10+(i%18),custom:false}));localStorage.setItem(KEYS.products,JSON.stringify(p))}return p}
function saveProducts(p){localStorage.setItem(KEYS.products,JSON.stringify(p))}function getCart(){return JSON.parse(localStorage.getItem(KEYS.cart)||'[]')}function saveCart(c){localStorage.setItem(KEYS.cart,JSON.stringify(c));updateCartCount()}function getWish(){return JSON.parse(localStorage.getItem(KEYS.wish)||'[]')}function money(n){return '৳'+Number(n||0).toLocaleString('en-BD')}
function toast(s){const t=document.getElementById('toast');if(!t)return;t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function updateCartCount(){document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=getCart().reduce((a,b)=>a+b.qty,0))}
function productCard(p){const w=getWish().includes(p.id);return `<article class="product"><${p.discount?'span':'div'} class="badge">${p.discount?p.discount+'% OFF':''}</${p.discount?'span':'div'}><a href="product-details.html?id=${encodeURIComponent(p.id)}"><img class="product-img" src="${p.image}" alt="${esc(p.name)}" loading="lazy"></a><div class="product-body"><div class="rating">${'★'.repeat(p.rating||5)}${'☆'.repeat(5-(p.rating||5))}</div><h3><a href="product-details.html?id=${encodeURIComponent(p.id)}">${esc(p.name)}</a></h3><div><span class="price">${money(p.price)}</span>${p.oldPrice?`<span class="old">${money(p.oldPrice)}</span>`:''}</div><small style="color:var(--muted)">Seller: ${esc(p.seller||'Noki Seller')} · Stock: ${p.stock}</small><div class="actions"><button class="btn btn-primary" onclick="addToCart('${p.id}')">🛒 Add</button><button class="btn heart" onclick="toggleWish('${p.id}')">${w?'❤️':'♡'}</button></div></div></article>`}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function addToCart(id,qty=1){const p=getProducts().find(x=>x.id===id);if(!p)return;if(p.stock<=0){toast('Out of stock');return}let c=getCart(),item=c.find(x=>x.id===id);if(item)item.qty=Math.min(item.qty+qty,p.stock);else c.push({id,qty:Math.min(qty,p.stock)});saveCart(c);toast('Added to cart 🛒')}
function toggleWish(id){let w=getWish();w=w.includes(id)?w.filter(x=>x!==id):[...w,id];localStorage.setItem(KEYS.wish,JSON.stringify(w));toast(w.includes(id)?'Added to wishlist ❤️':'Removed from wishlist');renderPage()}
function renderPage(){updateCartCount();const page=document.body.dataset.page; if(page==='home')renderHome();if(page==='products')renderProducts();if(page==='details')renderDetails();if(page==='cart')renderCart();if(page==='seller')renderSeller();}
function renderHome(){const p=getProducts();const f=document.getElementById('flashGrid'),g=document.getElementById('productGrid');if(f)f.innerHTML=p.slice(0,4).map(productCard).join('');if(g)g.innerHTML=p.slice(4,12).map(productCard).join('')}
function renderProducts(){const p=getProducts(),g=document.getElementById('productGrid');if(!g)return;const q=new URLSearchParams(location.search).get('cat');if(q&&document.getElementById('catFilter'))document.getElementById('catFilter').value=q;function apply(){let list=getProducts(),cat=document.getElementById('catFilter')?.value||'',s=(document.getElementById('productSearch')?.value||'').toLowerCase();list=list.filter(x=>(!cat||x.category===cat)&&(!s||x.name.toLowerCase().includes(s)||x.category.toLowerCase().includes(s)));g.innerHTML=list.length?list.map(productCard).join(''):'<div class="empty" style="grid-column:1/-1">No products found.</div>'}document.getElementById('applyFilters')?.addEventListener('click',apply);document.getElementById('productSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')apply()});apply()}
function renderDetails(){const box=document.getElementById('details');if(!box)return;const id=new URLSearchParams(location.search).get('id'),p=getProducts().find(x=>x.id===id);if(!p){box.innerHTML='<div class="empty"><h2>Product not found</h2><a class="btn btn-primary" href="products.html">Back to products</a></div>';return}box.innerHTML=`<div class="detail"><div><img src="${p.image}" alt="${esc(p.name)}"></div><div><div class="rating">${'★'.repeat(p.rating||5)}${'☆'.repeat(5-(p.rating||5))}</div><h1>${esc(p.name)}</h1><p><span class="price">${money(p.price)}</span> ${p.oldPrice?`<span class="old">${money(p.oldPrice)}</span>`:''}</p><p>Category: <b>${esc(p.category)}</b></p><p>Seller: <b>${esc(p.seller||'Noki Seller')}</b></p><p>Stock: <b>${p.stock>0?p.stock+' available':'Out of stock'}</b></p><div class="notice">Demo marketplace: ordering and payment are simulated in your browser.</div><h3>Description</h3><p>${esc(p.description)}</p><h3>Specifications</h3><div class="specs">${esc(p.specs||'Not provided')}</div><div class="actions"><button class="btn btn-primary" onclick="addToCart('${p.id}')">🛒 Add to Cart</button><button class="btn" onclick="buyNow('${p.id}')">⚡ Buy Now</button><button class="btn heart" onclick="toggleWish('${p.id}')">${getWish().includes(p.id)?'❤️':'♡'}</button></div></div></div>`}
function buyNow(id){addToCart(id);location.href='cart.html?checkout=1'}
function renderCart(){const list=document.getElementById('cartList'),sum=document.getElementById('cartSummary');if(!list)return;const ps=getProducts(),c=getCart().map(i=>({...i,p:ps.find(p=>p.id===i.id)})).filter(x=>x.p);if(!c.length){list.innerHTML='<div class="empty"><h2>Your cart is empty</h2><a class="btn btn-primary" href="products.html">Shop Products</a></div>';if(sum)sum.innerHTML='';return}let total=0;list.innerHTML=c.map(x=>{const line=x.p.price*x.qty;total+=line;return `<div class="cart-item"><img src="${x.p.image}" alt=""><div style="flex:1"><h3>${esc(x.p.name)}</h3><p>${money(x.p.price)} × ${x.qty}</p><div class="qty"><button onclick="changeQty('${x.id}',-1)">−</button><b>${x.qty}</b><button onclick="changeQty('${x.id}',1)">+</button><button class="btn" onclick="removeCart('${x.id}')">Remove</button></div></div><b>${money(line)}</b></div>`}).join('');if(sum)sum.innerHTML=`<h2>Order Summary</h2><p>Items: ${c.reduce((a,x)=>a+x.qty,0)}</p><h2>Total: ${money(total)}</h2><button class="btn btn-primary" onclick="openCheckout()">Proceed to Checkout</button>`;if(new URLSearchParams(location.search).get('checkout')==='1')setTimeout(openCheckout,100)}
function changeQty(id,d){let c=getCart(),i=c.find(x=>x.id===id),p=getProducts().find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)c=c.filter(x=>x.id!==id);else if(p)i.qty=Math.min(i.qty,p.stock);saveCart(c);renderCart()}
function removeCart(id){saveCart(getCart().filter(x=>x.id!==id));renderCart();toast('Removed from cart')}
function openCheckout(){const m=document.getElementById('checkoutModal');if(m)m.style.display='flex'}function closeCheckout(){const m=document.getElementById('checkoutModal');if(m)m.style.display='none'}
function checkout(e){e.preventDefault();const c=getCart(),ps=getProducts();if(!c.length)return;const data=Object.fromEntries(new FormData(e.target).entries());data.items=c;data.total=c.reduce((s,i)=>s+(ps.find(p=>p.id===i.id)?.price||0)*i.qty,0);data.id='NOKI-'+Date.now();localStorage.setItem(KEYS.order,JSON.stringify(data));c.forEach(i=>{const p=ps.find(p=>p.id===i.id);if(p)p.stock=Math.max(0,p.stock-i.qty)});saveProducts(ps);saveCart([]);closeCheckout();document.getElementById('orderSuccess').style.display='block';window.scrollTo({top:0,behavior:'smooth'})}
function renderSeller(){const list=document.getElementById('sellerList');if(list){const p=getProducts().filter(x=>x.custom);list.innerHTML=p.length?p.map(x=>`<div class="seller-item"><img src="${x.image}" alt=""><div style="flex:1"><b>${esc(x.name)}</b><p>${money(x.price)} · Stock ${x.stock}</p></div><a class="btn" href="seller.html?edit=${encodeURIComponent(x.id)}">Edit</a><button class="btn" onclick="deleteProduct('${x.id}')">Delete</button></div>`).join(''):'<div class="empty">No seller products yet.</div>'}const form=document.getElementById('sellerForm');if(form){const id=new URLSearchParams(location.search).get('edit');if(id)loadEdit(id);form.addEventListener('submit',saveSeller)} }
function loadEdit(id){const p=getProducts().find(x=>x.id===id);if(!p)return;['name','category','price','oldPrice','stock','seller','description','specs'].forEach(k=>{const el=document.getElementById('f_'+k);if(el)el.value=p[k]??''});document.getElementById('editId').value=id;const prev=document.getElementById('preview');if(prev&&p.image){prev.src=p.image;prev.style.display='block'} }
function saveSeller(e){e.preventDefault();const form=e.target,id=document.getElementById('editId').value||'seller-'+Date.now(),file=document.getElementById('image')?.files?.[0],base={id,name:document.getElementById('f_name').value.trim(),category:document.getElementById('f_category').value,price:Number(document.getElementById('f_price').value),oldPrice:Number(document.getElementById('f_oldPrice').value)||0,stock:Number(document.getElementById('f_stock').value),seller:document.getElementById('f_seller').value.trim(),description:document.getElementById('f_description').value.trim(),specs:document.getElementById('f_specs').value.trim(),rating:5,discount:0,custom:true};const p=getProducts(),old=p.find(x=>x.id===id);const finish=image=>{base.image=image||old?.image||'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80';if(old)Object.assign(old,base);else p.push(base);saveProducts(p);toast('Product saved');setTimeout(()=>location.href='seller-dashboard.html',500)};if(file){const r=new FileReader();r.onload=()=>finish(r.result);r.readAsDataURL(file)}else finish()}
function deleteProduct(id){if(!confirm('Delete this demo product?'))return;saveProducts(getProducts().filter(x=>x.id!==id));renderPage();toast('Product deleted')}
function init(){const menu=document.querySelector('[data-open-menu]'),panel=document.querySelector('.category-panel');menu?.addEventListener('click',()=>panel?.classList.toggle('open'));const form=document.getElementById('checkoutForm');form?.addEventListener('submit',checkout);document.getElementById('image')?.addEventListener('change',e=>{const f=e.target.files[0],p=document.getElementById('preview');if(f&&p){p.src=URL.createObjectURL(f);p.style.display='block'}});getProducts();renderPage()}
init();
